{% set name = "napari-annotatorj" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-annotatorj-{{ version }}.tar.gz
  sha256: b26d2e4e8ae9294657299f3128bf8f426932bbc16267cc63d5b95d1d23a739af

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - imagecodecs
    - keras
    - napari-plugin-engine >=0.1.4
    - numpy
    - opencv >=4.5.5
    - python >=3.7
    - roifile
    - scikit-image
    - tensorflow >=2.5.0
    - tifffile
    - qtpy
    - napari
    - tqdm

test:
  imports:
    - napari_annotatorj
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/spreka/napari-annotatorj
  summary: The napari adaptation of the ImageJ/Fiji plugin AnnotatorJ for easy image annotation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spreka
    - goanpeca
    - jaimergp
